title: Jahun Lee, Ph.D. Student
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Jahun Lee"
job: "Ph.D. Student in Public Administration"


#phone_number: 012-345-6789
address: University of Illinois Chicago
#linkedin_username: linkedin
#github_username: github
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
# blog_url: homepage-url
email: jlee903@uic.edu


# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/
  - _data-exclusion/


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
